<script lang="ts">
 import { onMount } from 'svelte';
 import { supabase } from '$lib/supabaseClient';

 // ١. گۆڕاوێن سەرەکی
 let doctorId = $state(0);
 let isLoading = $state(true);
 
 // هەلبژارتنا هەیڤ و ساڵێ
 let selectedMonth = $state(new Date().getMonth() + 1); // هەیڤا نوکە
 let selectedYear = $state(new Date().getFullYear());

 // ئامارێن هەیڤا هەلبژارتی
 let monthlyStats = $state({
  patients: 0,
  income: 0,
  expenses: 0,
  profit: 0
 });

 let recentActivity = $state<any[]>([]);

 const months = [
  { id: 1, name: 'January' }, { id: 2, name: 'February' }, { id: 3, name: 'March' },
  { id: 4, name: 'April' }, { id: 5, name: 'May' }, { id: 6, name: 'June' },
  { id: 7, name: 'July' }, { id: 8, name: 'August' }, { id: 9, name: 'September' },
  { id: 10, name: 'October' }, { id: 11, name: 'November' }, { id: 12, name: 'December' }
 ];

 onMount(async () => {
  const storedId = localStorage.getItem('doctor_id');
  if (storedId) {
   doctorId = Number(storedId);
   await loadDashboard();
  }
 });

 // 📊 فانکشنا سەرەکی بۆ ئینانا ئامارێن هەر هەیڤەکێ
 async function loadDashboard() {
  isLoading = true;
  
  // دیارکرنا دەسپێک و دووماهیا هەیڤا هەلبژارتی
  const startDate = new Date(selectedYear, selectedMonth - 1, 1).toISOString();
  const endDate = new Date(selectedYear, selectedMonth, 0, 23, 59, 59).toISOString();

  // ١. ئینانا داهاتێ هەیڤێ (Income from Medical Records)
  const { data: records } = await supabase.from('medical_records')
   .select('fee, created_at, diagnosis, patients(name)')
   .eq('doctor_id', doctorId)
   .gte('created_at', startDate)
   .lte('created_at', endDate);

  // ٢. ئینانا خەرجیێن هەیڤێ (Expenses)
  const { data: exps } = await supabase.from('expenses')
   .select('amount')
   .eq('doctor_id', doctorId)
   .gte('created_at', startDate)
   .lte('created_at', endDate);

  // حسابکرن
  if (records) {
   monthlyStats.patients = records.length;
   monthlyStats.income = records.reduce((s, r) => s + (Number(r.fee) || 0), 0);
   recentActivity = records.slice(-5).reverse();
  } else {
   monthlyStats.patients = 0; monthlyStats.income = 0;
  }

  if (exps) {
   monthlyStats.expenses = exps.reduce((s, e) => s + (Number(e.amount) || 0), 0);
  } else {
   monthlyStats.expenses = 0;
  }

  monthlyStats.profit = monthlyStats.income - monthlyStats.expenses;
  isLoading = false;
 }

 // 🖨️ چاپکرنا ڕاپۆرتا پڕۆفیشناڵ یا هەیڤانە
 function printMonthlyReport() {
  const monthName = months.find(m => m.id === selectedMonth)?.name;
  const win = window.open('', '', 'width=900,height=1000');
  win?.document.write(`
   <div style="font-family:sans-serif; padding:50px; border:2px solid #4f46e5; border-radius:15px;">
    <h1 style="text-align:center; color:#4f46e5; margin-bottom:5px;">Monthly Performance Report</h1>
    <p style="text-align:center; margin-top:0;">${monthName} ${selectedYear}</p>
    <hr>
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:20px; margin:30px 0;">
     <div style="padding:15px; background:#f0f9ff; border-radius:10px;"><b>Total Patients:</b> ${monthlyStats.patients}</div>
     <div style="padding:15px; background:#f0fdf4; border-radius:10px;"><b>Monthly Income:</b> $${monthlyStats.income}</div>
     <div style="padding:15px; background:#fef2f2; border-radius:10px;"><b>Monthly Expenses:</b> $${monthlyStats.expenses}</div>
     <div style="padding:15px; background:#eef2ff; border-radius:10px;"><b>Net Profit:</b> $${monthlyStats.profit}</div>
    </div>
    <p style="text-align:center; color:#666; font-size:12px;">Generated by E-Clinic Digital System</p>
   </div>
  `);
  win?.document.close();
  win?.print();
 }
</script>

<div class="dashboard">
 <!-- Top Control Bar -->
 <header class="dashboard-header">
  <div class="title-area">
   <h1>Performance Overview 🚀</h1>
   <p>ئامارێن هوور یێن کلینیکێ ل دویڤ هەیڤان</p>
  </div>
  
  <div class="controls">
   <select bind:value={selectedMonth} onchange={loadDashboard}>
    {#each months as m}<option value={m.id}>{m.name}</option>{/each}
   </select>
   <select bind:value={selectedYear} onchange={loadDashboard}><option value={2025}>2025</option>
    <option value={2026}>2026</option>
   </select>
   <button class="print-btn" onclick={printMonthlyReport}>🖨️ Print Report</button>
  </div>
 </header>

 {#if isLoading}
  <div class="loader">Loading Analytics...</div>
 {:else}
  <!-- Stats Grid -->
  <div class="stats-grid">
   <div class="stat-card blue">
    <div class="icon-bg">👥</div>
    <div class="info">
     <span>Total Patients</span>
     <h3>{monthlyStats.patients}</h3>
    </div>
   </div>
   <div class="stat-card green">
    <div class="icon-bg">💰</div>
    <div class="info">
     <span>Total Income</span>
     <h3>${monthlyStats.income}</h3>
    </div>
   </div>
   <div class="stat-card red">
    <div class="icon-bg">💸</div>
    <div class="info">
     <span>Expenses</span>
     <h3>${monthlyStats.expenses}</h3>
    </div>
   </div>
   <div class="stat-card gold">
    <div class="icon-bg">📈</div>
    <div class="info">
     <span>Net Profit</span>
     <h3>${monthlyStats.profit}</h3>
    </div>
   </div>
  </div>

  <div class="main-grid">
   <!-- Comparison Chart (CSS Based) -->
   <div class="card glass chart-card">
    <h3>📊 Income vs Expenses</h3>
    <div class="bar-container">
     <div class="bar-row">
      <!-- svelte-ignore a11y_label_has_associated_control -->
      <label>Income</label>
      <div class="bar-bg"><div class="bar-fill green" style="width: {monthlyStats.income > 0 ? '100%' : '0%'}"></div></div>
      <span class="val">${monthlyStats.income}</span>
     </div>
     <div class="bar-row">
      <!-- svelte-ignore a11y_label_has_associated_control -->
      <label>Expenses</label>
      <div class="bar-bg"><div class="bar-fill red" style="width: {(monthlyStats.expenses / (monthlyStats.income || 1)) * 100}%"></div></div>
      <span class="val">${monthlyStats.expenses}</span>
     </div>
    </div>
    <p class="profit-footer">The profit margin for this month is <b>${monthlyStats.profit}</b></p>
   </div>

   <!-- Recent Log -->
   <div class="card glass list-card">
    <h3>🕒 Recent Month Activity</h3>
    <div class="activity-list">
     {#each recentActivity as item}
      <div class="item">
       <div class="avatar">{item.patients?.name[0]}</div>
       <div class="details">
        <b>{item.patients?.name}</b>
        <span>{item.diagnosis}</span>
       </div>
       <div class="price">+${item.fee}</div>
      </div>
     {:else}
      <p class="empty">No records for this month.</p>
     {/each}
    </div>
   </div>
  </div>
 {/if}
</div>

<style>
 .dashboard { color: var(--text); animation: fadeIn 0.5s ease; padding: 5px; }
 @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }

 .dashboard-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 35px; flex-wrap: wrap; gap: 20px; }
 .dashboard-header h1 { font-size: 1.8rem; font-weight: 900; color: #4f46e5; margin: 0; }
 
 .controls { display: flex; gap: 10px; }
 select { padding: 10px 15px; border-radius: 12px; border: 1px solid #ddd; background: white; color: #333; font-weight: bold; cursor: pointer; }
 .print-btn { background: #111827; color: white; border: none; padding: 10px 20px; border-radius: 12px; cursor: pointer; font-weight: bold; }

 .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; margin-bottom: 30px; }
 .stat-card { padding: 25px; border-radius: 25px; display: flex; align-items: center; gap: 20px; color: white; box-shadow: 0 10px 20px -5px rgba(0,0,0,0.1); }
 
 .blue { background: linear-gradient(135deg, #6366f1, #4338ca); }
 .green { background: linear-gradient(135deg, #10b981, #059669); }
 .red { background: linear-gradient(135deg, #f43f5e, #be123c); }
 .gold { background: linear-gradient(135deg, #f59e0b, #d97706); }

 .icon-bg { width: 55px; height: 55px; background: rgba(255,255,255,0.2); border-radius: 18px; display: flex; align-items: center; justify-content: center; font-size: 2rem; }
 .info span { font-size: 0.8rem; font-weight: 600; opacity: 0.9; }
 .info h3 { margin: 2px 0 0; font-size: 1.8rem; font-weight: 900; }

 .main-grid { display: grid; grid-template-columns: 1.2fr 1fr; gap: 25px; }
 @media (max-width: 1000px) { .main-grid { grid-template-columns: 1fr; } }

 .card { background: var(--card, white); padding: 30px; border-radius: 28px; border: 1px solid var(--border, #eee); box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02); }
 
 /* Chart Styling */
 .bar-container { display: flex; flex-direction: column; gap: 25px; margin: 30px 0; }
 .bar-row { display: flex; align-items: center; gap: 15px; }
 .bar-row label { width: 80px; font-weight: bold; font-size: 0.85rem; }
 .bar-bg { flex: 1; background: #f1f5f9; height: 12px; border-radius: 6px; overflow: hidden; }
 .bar-fill { height: 100%; transition: width 1s ease-in-out; }
 .bar-fill.green { background: #10b981; }
 .bar-fill.red { background: #f43f5e; }
 .val { width: 80px; font-weight: 900; color: #4f46e5; text-align: right; }
 .profit-footer { text-align: center; font-size: 0.9rem; opacity: 0.6; margin-top: 20px; }

 /* Activity List */
 .activity-list { display: flex; flex-direction: column; gap: 12px; margin-top: 20px; }
 .item { display: flex; align-items: center; gap: 15px; padding: 12px; background: rgba(0,0,0,0.02); border-radius: 18px; border: 1px solid transparent; }
 .avatar { width: 40px; height: 40px; background: #e0e7ff; color: #4f46e5; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 800; }
 .details { flex: 1; display: flex; flex-direction: column; }
 .details b { font-size: 0.9rem; }
 .details span { font-size: 0.75rem; opacity: 0.5; }
 .price { font-weight: 900; color: #10b981; }

 :global(.dark-mode) .card, :global(.dark-mode) .item { background: #1e293b; border-color: #334155; }
 :global(.dark-mode) .bar-bg { background: #334155; }
 :global(.dark-mode) select { background: #1e293b; color: white; border-color: #334155; }
</style>