<script lang="ts">
 import { onMount } from 'svelte';
 import { supabase } from '$lib/supabaseClient';

 // ١. گۆڕاوێن ئاماران
 let doctorId = $state(0);
 let isLoading = $state(true);
 
 // هەلبژارتنا هەیڤێ بۆ ڕاپۆرتێ
 let selectedMonth = $state(new Date().getMonth() + 1);
 let selectedYear = $state(new Date().getFullYear());

 let stats = $state({ totalP: 0, todayInc: 0, totalInc: 0, totalExp: 0, profit: 0 });
 let monthlyReport = $state({ patients: 0, income: 0, expenses: 0, profit: 0 });
 let recentActivity = $state<any[]>([]);

 const months = [
  { id: 1, name: 'January' }, { id: 2, name: 'February' }, { id: 3, name: 'March' },
  { id: 4, name: 'April' }, { id: 5, name: 'May' }, { id: 6, name: 'June' },
  { id: 7, name: 'July' }, { id: 8, name: 'August' }, { id: 9, name: 'September' },
  { id: 10, name: 'October' }, { id: 11, name: 'November' }, { id: 12, name: 'December' }
 ];

 onMount(async () => {
  const storedId = localStorage.getItem('doctor_id');
  if (storedId) {
   doctorId = Number(storedId);
   await loadDashboard();
  }
 });

 async function loadDashboard() {
  isLoading = true;
  const now = new Date();
  const todayStr = now.toDateString();

  // ١. ئینانا هەمی داتایان ژ داتابەیسێ
  const { count: pCount } = await supabase.from('patients').select('*', { count: 'exact', head: true }).eq('doctor_id', doctorId);
  const { data: records } = await supabase.from('medical_records').select('fee, created_at, patients(name)').eq('doctor_id', doctorId);
  const { data: exps } = await supabase.from('expenses').select('amount, created_at').eq('doctor_id', doctorId);

  // ٢. حسابکرنا داتایان ب لۆجیکەکێ ب هێز
  if (records) {
   let tInc = 0; let dInc = 0; let mInc = 0; let mPat = 0;
   
   records.forEach(r => {
    const rFee = Number(r.fee) || 0;
    tInc += rFee;

    if (r.created_at) {
     const rDate = new Date(r.created_at);
     if (rDate.toDateString() === todayStr) dInc += rFee;
     if ((rDate.getMonth() + 1) === selectedMonth && rDate.getFullYear() === selectedYear) {
      mInc += rFee;
      mPat++;
     }
    } else {
     // ئەگەر تاریخ NULL بوو، ل داهاتێ گشتی زێدە بکە دا بەرزە نەبیت
     mInc += rFee;
    }
   });

   stats.totalInc = tInc;
   stats.todayInc = dInc;
   monthlyReport.income = mInc;
   monthlyReport.patients = mPat;
   recentActivity = records.slice(-5).reverse();
  }

  if (exps) {
   let tExp = 0; let mExp = 0;
   exps.forEach(e => {
    const eAmt = Number(e.amount) || 0;
    tExp += eAmt;
    if (e.created_at) {
     const eDate = new Date(e.created_at);
     if ((eDate.getMonth() + 1) === selectedMonth && eDate.getFullYear() === selectedYear) mExp += eAmt;
    }
   });
   stats.totalExp = tExp;
   monthlyReport.expenses = mExp;
  }

  stats.totalP = pCount || 0;
  stats.profit = stats.totalInc - stats.totalExp;
  monthlyReport.profit = monthlyReport.income - monthlyReport.expenses;
  isLoading = false;
 }

 // 🖨️ چاپکرنا ڕاپۆرتا دارایی یا هەیڤانە ب شێوازەکێ پڕۆفیشناڵ
 function printReport() {
  const monthName = months.find(m => m.id === selectedMonth)?.name;
  const win = window.open('', '', 'width=900,height=1000');
  win?.document.write(`
   <div style="font-family:sans-serif; padding:50px; border:2px solid #4f46e5; border-radius:15px;">
    <h1 style="text-align:center; color:#4f46e5; margin-bottom:5px;">Monthly Financial Report</h1>
    <p style="text-align:center; margin-top:0; font-weight:bold;">${monthName} ${selectedYear}</p>
    <hr style="border:1px solid #eee; margin:20px 0;">
    <div style="display:grid; grid-template-columns:1fr 1fr; gap:20px;">
     <div style="padding:20px; background:#f0f9ff; border-radius:10px;">
      <h3 style="margin:0; color:#0369a1;">Earnings</h3>
      <p style="font-size:24px; font-weight:bold; margin:10px 0;">$${monthlyReport.income}</p>
      <small>Total visits: ${monthlyReport.patients}</small>
     </div>
     <div style="padding:20px; background:#fef2f2; border-radius:10px;">
      <h3 style="margin:0; color:#991b1b;">Expenses</h3>
      <p style="font-size:24px; font-weight:bold; margin:10px 0;">$${monthlyReport.expenses}</p>
     </div>
    </div>
    <div style="margin-top:30px; padding:25px; background:#f0fdf4; border-radius:10px; text-align:center;">
     <h2 style="margin:0; color:#15803d;">Net Profit</h2>
     <p style="font-size:35px; font-weight:900; margin:10px 0;">$${monthlyReport.profit}</p>
    </div>
    <div style="margin-top:50px; border-top:1px solid #ddd; padding-top:20px; display:flex; justify-content:space-between; font-size:12px; color:#666;">
     <span>Generated by E-Clinic Digital System</span>
     <span>Signature: _________________</span>
    </div>
   </div>
  `);
  win?.document.close();
  win?.print();
 }
</script>

<div class="dashboard">
 <header class="dash-header">
  <div class="title">
   <h1>Clinic Analytics 📊</h1>
   <p>کورتیا دارایی و گەشەیا کلینیکێ</p>
  </div>
  <div class="actions">
   <select bind:value={selectedMonth} onchange={loadDashboard}>
    {#each months as m}<option value={m.id}>{m.name}</option>{/each}
   </select>
   <button class="btn-print" onclick={printReport}>🖨️ Print A4 Report</button>
   <button class="btn-refresh" onclick={loadDashboard}>🔄</button>
  </div>
 </header>

 {#if isLoading}
  <div class="loading">📊 Loading data from database...</div>
 {:else}
  <!-- کارتێن ئاماران -->
  <div class="stats-grid">
   <div class="card blue"><p>Total Patients</p><h3>{stats.totalP}</h3></div>
   <div class="card green"><p>Today's Income</p><h3>${stats.todayInc}</h3></div>
   <div class="card indigo"><p>Total Income</p><h3>${stats.totalInc}</h3></div>
   <div class="card red"><p>Total Expenses</p><h3>${stats.totalExp}</h3></div>
  </div>

  <div class="main-grid">
   <!-- ڕاپۆرتا هەیڤێ -->
   <div class="glass-card">
    <div class="card-head">
     <h3>📈 Monthly Summary</h3>
     <span class="badge">{months.find(m => m.id === selectedMonth)?.name}</span>
    </div>
    <div class="monthly-stats">
     <div class="row"><span>Monthly Income:</span> <b style="color:#10b981">+${monthlyReport.income}</b></div>
     <div class="row"><span>Monthly Expenses:</span> <b style="color:#f43f5e">-${monthlyReport.expenses}</b></div>
     <div class="total-row">
      <p>Monthly Net Profit</p>
      <h2 style="color: {monthlyReport.profit >= 0 ? '#10b981' : '#f43f5e'}">${monthlyReport.profit}</h2>
     </div>
    </div>
   </div>

   <!-- نویترین چالاکی -->
   <div class="glass-card">
    <h3>🕒 Recent Activity</h3>
    <div class="activity-list">
     {#each recentActivity as item}
      <div class="item">
       <b>{item.patients?.name || 'Patient'}</b>
       <span class="price">+${item.fee}</span>
      </div>
     {:else}
      <p class="empty">No records found for this doctor.</p>
     {/each}
    </div>
   </div>
  </div>
 {/if}
</div>

<style>
 .dashboard { color: var(--text); padding: 10px; font-family: sans-serif; }
 .dash-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; flex-wrap: wrap; gap: 15px; }
 .dash-header h1 { margin: 0; color: #4f46e5; }
 
 .actions { display: flex; gap: 10px; }
 select { padding: 10px; border-radius: 10px; border: 1px solid #ddd; background: white; color: black; font-weight: bold; }
 .btn-print { background: #111827; color: white; border: none; padding: 10px 20px; border-radius: 10px; cursor: pointer; font-weight: bold; }
 .btn-refresh { background: #f3f4f6; border: 1px solid #ddd; padding: 10px 15px; border-radius: 10px; cursor: pointer; }

 .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 20px; margin-bottom: 30px; }
 .card { padding: 25px; border-radius: 20px; color: white; text-align: center; box-shadow: 0 10px 15px rgba(0,0,0,0.1); transition: 0.3s; }
 .card:hover { transform: translateY(-5px); }
 
 .blue { background: linear-gradient(135deg, #4f46e5, #3b82f6); }
 .green { background: linear-gradient(135deg, #10b981, #059669); }
 .indigo { background: linear-gradient(135deg, #6366f1, #4f46e5); }
 .red { background: linear-gradient(135deg, #f43f5e, #be123c); }
 
 .card h3 { margin: 10px 0 0; font-size: 2rem; font-weight: 900; }
 .card p { margin: 0; font-size: 0.8rem; font-weight: bold; opacity: 0.8; text-transform: uppercase; }

 .main-grid { display: grid; grid-template-columns: 1.2fr 1fr; gap: 25px; }
 @media (max-width: 1000px) { .main-grid { grid-template-columns: 1fr; } }

 .glass-card { background: var(--card, white); padding: 30px; border-radius: 25px; border: 1px solid var(--border, #eee); box-shadow: 0 4px 6px rgba(0,0,0,0.02); }
 .card-head { display: flex; justify-content: space-between; margin-bottom: 20px; }
 .badge { background: #eef2ff; color: #4f46e5; padding: 5px 12px; border-radius: 20px; font-weight: bold; font-size: 0.8rem; }

 .row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid rgba(0,0,0,0.05); }
 .total-row { text-align: center; margin-top: 25px; padding-top: 20px; border-top: 2px dashed #eee; }
 .total-row h2 { font-size: 2.5rem; margin: 5px 0; font-weight: 900; }

 .item { display: flex; justify-content: space-between; padding: 12px; background: rgba(0,0,0,0.03); border-radius: 12px; margin-bottom: 10px; }
 .price { color: #10b981; font-weight: bold; }
 .loading { text-align: center; padding: 100px; font-weight: bold; }

 :global(.dark-mode) .glass-card, :global(.dark-mode) .item { background: #1e293b; border-color: #334155; }
 :global(.dark-mode) select { background: #1e293b; color: white; border-color: #334155; }
</style>