<script lang="ts">
	import { onMount } from 'svelte';
	import { supabase } from '$lib/supabaseClient';

	let patients = $state<any[]>([]);
	let availableTests = $state<string[]>([]);
	let selectedPatient = $state<any>(null);
	let selectedTests = $state<string[]>([]);
	let doctorId = $state(0);
	let docInfo = $state<any>(null);

	async function loadLabData() {
		const id = localStorage.getItem('doctor_id');
		if (!id) return;
		doctorId = Number(id);

		// ١. ئینانا زانیاریێن تەمام یێن دکتۆری (ناڤ، نیشان، فەحسێن ڕێپێدای)
		const { data: doc } = await supabase.from('doctors').select('*').eq('id', doctorId).single();
		if (doc) {
			docInfo = doc;
			// گۆهۆڕینا فەحسان بۆ لیستە
			availableTests = doc.allowed_tests ? doc.allowed_tests.split(',').map((t: string) => t.trim()) : [];
		}

		// ٢. ئینانا نەخۆشێن وی دکتۆری
		const { data: p } = await supabase.from('patients').select('*').eq('doctor_id', doctorId).order('name');
		if (p) patients = p;
	}

	onMount(loadLabData);

	function toggle(t: string) {
		selectedTests = selectedTests.includes(t) ? selectedTests.filter(i => i !== t) : [...selectedTests, t];
	}

	// 🖨️ چاپکرنا فەرمی یا فەحسان ب تمامى ڕێکوپێک
	function printLabOrder() {
		if (!selectedPatient || selectedTests.length === 0) return alert("Select patient and tests");
		
		const win = window.open('', '', 'width=900,height=1100');
		win?.document.write(`
			<html>
			<head>
				<style>
					@page { size: A4; margin: 15mm; }
					body { font-family: sans-serif; padding: 30px; color: #333; }
					.header { display: flex; justify-content: space-between; border-bottom: 4px solid #10b981; padding-bottom: 15px; margin-bottom: 25px; }
					.clinic-info h1 { margin: 0; color: #10b981; font-size: 26px; text-transform: uppercase; }
					.patient-box { background: #f8fafc; padding: 20px; border-radius: 12px; display: grid; grid-template-columns: 1fr 1fr; gap: 15px; border: 1px solid #e2e8f0; margin-bottom: 30px; }
					.test-list { min-height: 450px; font-size: 1.2rem; line-height: 2.5; list-style: none; padding: 0; }
					.footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; display: flex; justify-content: space-between; font-size: 12px; }
				</style>
			</head>
			<body>
				<div class="header">
					<div>
						<h1>${docInfo?.clinic_name || 'E-CLINIC'}</h1>
						<p style="font-size:18px; font-weight:bold; margin:5px 0;">Dr. ${docInfo?.doctor_name || 'Doctor'}</p>
					</div>
					<div style="text-align:right; font-size:13px;">
						${docInfo?.clinic_address || ''}<br>Tel: ${docInfo?.clinic_phone || ''}
					</div>
				</div>

				<div class="patient-box">
					<div><b>Patient:</b> ${selectedPatient.name}</div>
					<div><b>Age/Gender:</b> ${selectedPatient.age}Y / ${selectedPatient.gender}</div>
					<div><b>Phone:</b> ${selectedPatient.phone}</div>
					<div><b>Date:</b> ${new Date().toLocaleDateString('en-GB')}</div>
				</div>

				<h3>Investigative Lab Request:</h3>
				<ul class="test-list">
					${selectedTests.map(t => `<li>[ ] ${t}</li>`).join('')}
				</ul>

				<div class="footer">
					<p>Generated by E-Clinic Digital System</p>
					<div style="text-align:center; width:200px; border-top:2px solid #333; padding-top:5px; font-weight:bold;">Doctor's Signature</div>
				</div>
				<script>window.print(); window.close();<\/script>
			</body>
			</html>
		`);
		win?.document.close();
	}
</script>

<div class="lab-page">
	<h2>🧪 Laboratory Requests</h2>

	<div style="display:grid; grid-template-columns: 2fr 1fr; gap:20px;">
		<div class="card" style="background:white; padding:25px; border-radius:15px; border:1px solid #ddd;">
			<h3>1. Select Patient</h3>
			<select bind:value={selectedPatient} style="width:100%; padding:12px; border-radius:10px; margin-bottom:20px;">
				<option value={null}>-- Choose Patient --</option>
				{#each patients as p}<option value={p}>{p.name}</option>{/each}
			</select>

			<h3>2. Choose Investigations</h3>
			<div style="display:grid; grid-template-columns: 1fr 1fr; gap:10px;">
				{#each availableTests as t}
					<button 
						style="padding:12px; border-radius:10px; border:1px solid #ddd; cursor:pointer; text-align:left; background:{selectedTests.includes(t) ? '#10b981' : 'white'}; color:{selectedTests.includes(t) ? 'white' : 'black'}"
						onclick={() => toggle(t)}
					>
						{t}
					</button>
				{:else}
					<p style="color:red; font-size:0.8rem;">No tests assigned by Admin yet.</p>
				{/each}
			</div>
		</div>

		<div class="card" style="background:white; padding:25px; border-radius:15px; border:1px solid #ddd;">
			<h3>Order Summary</h3>
			{#if selectedPatient}
				<p>Patient: <b>{selectedPatient.name}</b></p>
				<button 
					style="width:100%; padding:15px; background:#10b981; color:white; border:none; border-radius:10px; cursor:pointer; font-weight:bold; margin-top:20px;"
					onclick={printLabOrder}
				>
					🖨️ Print Lab Order
				</button>
			{:else}
				<p style="color:#999;">Select a patient first.</p>
			{/if}
		</div>
	</div>
</div>